spring:
  application:
    name: batch


  datasource:
    url: jdbc:postgresql://localhost:5432/file-upload
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: postgres
    database: postgresql
    database-platform: org.hibernate.dialect.PostgeSQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 9090
